# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentus', '0002_auto_20170817_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentus.Cliente'),
        ),
    ]
